Fix call for String#present? which doesn't exist out of Rails
  Also, bump version to 0.1.9

  Using the integrate for non-Rails apps was raising the error:

    NoMethodError: undefined method `present?' for "":String

      if x.present? && x != USER

  String#present? is an extension added by ActiveSupport,
  and doesn't exist in pure Ruby.